/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LIYUE' at '16-3-7 下午9:15' with Gradle 2.11
 *
 * @author LIYUE, @date 16-3-7 下午9:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
